### ISSUE TITLE
USER STORY: As a shopper I can view a list of tours so that I can select which ones I want to go on

### ISSUE THREAD

**Issue by JennyDelaney** [JennyDelaney/pp5-JennyDelaney#1]
Epic: <epic>

As a **shopper** I can **view a list of tours** so that **I can select which ones I want to go on**

** Acceptance **

- [ ] - The tours page layout is clear and the menu makes it easy to sort tours by location on the website
- [ ] - Navigation to the various sorting options and functions is clear and easy to use
- [ ] - The homepage should be optimized for various devices and have no technical errors

**Tasks**

- [ ] Task 1 = Create a wireframe and design a homepage so it can be implemented
- [ ] Task 2 = Optimize the page for quick loading and device compatibility
- [ ] Task 3 = Leverage base.html content and sections (ccs, js etc).
